apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-recommender
  template:
    metadata:
      labels:
        app: playlist-recommender
    spec:
      containers:
      - name: model
        image: hlisboa/playlist-recommendation-model:latest
        imagePullPolicy: Always
      - name: api
        imagePullPolicy: Always
        image: hlisboa/playlist-recommendation-api:latest
        ports:
        - containerPort: 32185

      - name: frontend
        image: hlisboa/playlist-recommendation-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#  name: project2-pvc-henriquesousa
# spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: standard
#  resources:
#    requests:
#      storage: 1Gi
#  volumeName: project2-pv-henriquesousa
# ---
