name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: "Setup Python, Poetry and Dependencies"
      uses: packetcoders/action-setup-cache-python-poetry@main
      with:
        python-version: 3.12
        poetry-version: 1.2.2

    - name: Generate Itemsets
      run: poetry run python models/itemsets_generator.py
    - name: Run Python unittests
      run: |
        poetry run python -m unittest discover ./tests/unittests "*_test.py"

  publish-images:
    runs-on: ubuntu-latest
    needs: run-unittests
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push images
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        docker buildx create --use
        docker buildx inspect --bootstrap

        docker buildx build -t hlisboa/playlist-recommendation-api:latest -f dockerfiles/api.dockerfile --push .
        docker buildx build -t hlisboa/playlist-recommendation-model:latest -f dockerfiles/model.dockerfile --push .
        docker buildx build -t hlisboa/playlist-recommendation-frontend:latest -f dockerfiles/frontend.dockerfile --push .