name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: "Setup Python, Poetry and Dependencies"
      uses: packetcoders/action-setup-cache-python-poetry@main
      with:
        python-version: 3.12
        poetry-version: 1.2.2

    - name: Generate Itemsets
      run: poetry run python models/itemsets_generator.py
 